### PR TITLE
learners passbook

### PR DESCRIPTION
**Pull request by abhirupr123**
## DIKSHA

Digital Learners' Passbook

### Changes

Updated the author name

### Notes

Added email, linkedin and github

### CODE REVIEW

**Comment by abhirupr123** [comment]
> ## DIKSHA
> Digital Learners' Passbook
> 
> ### Changes
> Added Week 1 and 2 milestones and contributions
> 
> ### Notes
> Added screenshots of the UI.

**Comment by claddyk** [comment]
Hi @abhirupr123,
I think this PR is closeworthy by looking at the file changes.
You should reattempt to open a PR with proper changes made.
If you're not sure about how to do it, just go through the recording of the google meet that Shruti conducted.

**Comment by Shruti3004** [comment]
Hey @abhirupr123 please raise a another PR

**Comment by abhirupr123** [comment]
> Hey @abhirupr123 please raise a another PR

I have raised a new pr, this is the link - https://github.com/Code4GovTech/c4gt-milestones/pull/194

**Comment by abhirupr123** [comment]
I have made changes, this is the new pr - #194
<https://github.com/Code4GovTech/c4gt-milestones/pull/194>

**Pull request closed without merging**
