### PR TITLE
add week 6 milestones

### PR DESCRIPTION
**Pull request by goyalpramod**
## Project

Text2SQL

### CODE REVIEW

**Comment by goyalpramod** [comment]
@Apoorvgarg-creator Kindly check

**Comment by Apoorvgarg-creator** [comment]
> @Apoorvgarg-creator Kindly check

Kindly add PR link

**Comment by Apoorvgarg-creator** [comment]
and remove headings that aren't used

**Comment by goyalpramod** [comment]
@Apoorvgarg-creator the changes were made to the dataset itself, there was errors with that. Not with our code. So I have not made a pr for that yet. After the dataset itself is finalised I will push that. As for heading, I belive I have only added milestones. What should I remove?

**Comment by Apoorvgarg-creator** [comment]
Remove the screenshot, contribution and learnings headings

**Comment by goyalpramod** [comment]
@Apoorvgarg-creator done

**Pull request merged**
