### PR TITLE
My milestones mohd zaid

### PR DESCRIPTION
**Pull request by MDZAID123**
## Project

ABDM CONSENT MANAGEMENT

### Changes
WEEK4 MILESTONES

### Notes

If there are any further notes.

### CODE REVIEW

**Comment by MDZAID123** [comment]
resolved merge conflicts

**Comment by GeekGawd** [comment]
@MDZAID123 please remove yarn.lock from commit and kindly do the changes requested.

**Comment by MDZAID123** [comment]
actually there is some problem from my side so am currently created a new branch in my forked repo and cloned the new branch on my local system and them i will be doing changesd from there and then raising the pr from that new branch.

**Comment by MDZAID123** [comment]
should i close this pr plz guide me

**Pull request closed without merging**
