### PR TITLE
Aayush Sharma(Sunbird Obsrv): added milestone directory

### PR DESCRIPTION
**Pull request by SuperAayush**
## Project

Sunbird Obsrv - Setup of one-click installation of Obsrv

### Changes

- Added the milestones directory
- Added the introduction directory
- Added the setup directory
- Updated the socials
- Updated the author's name
- Updated the progress for weeks 1,2,3 and 4

cc - @Shruti3004 @shubhigupta991

### CODE REVIEW

**Comment by GeekGawd** [comment]
@SuperAayush I see you have added some images do you intend to use them.

**Comment by SuperAayush** [comment]
> @SuperAayush I see you have added some images do you intend to use them.

Yes

**Comment by GeekGawd** [comment]
@SuperAayush Please don't use gdrive download the images and place them in a asset folder see other people updates for reference

**Comment by SuperAayush** [comment]
> @SuperAayush Please don't use gdrive download the images and place them in a asset folder see other people updates for reference

Ohh wait let remove the images, I will directly use the gdrive link.

**Comment by SuperAayush** [comment]
Done!!

**Comment by SuperAayush** [comment]
> @SuperAayush Please don't use gdrive download the images and place them in a asset folder see other people updates for reference

I don't think gdrive would be a issue, have a lot at this file: https://github.com/Code4GovTech/c4gt-milestones/blob/main/docs/2023/Sunbird%20Lern/Integrate%20with%20non-Keycloak%20authentication%20system/updates/2023-07-07.md?plain=1

**Comment by GeekGawd** [comment]
@SuperAayush You are right, my bad!

**Pull request merged**
