### PR TITLE
Beckn energy interface

### PR DESCRIPTION
**Pull request by Sudheesh2609**
## Project

Beckn Energy Interface

### Changes

Weekly Updates: Updated Week 1,2  and 3

### CODE REVIEW

**Comment by GeekGawd** [comment]
@Sudheesh2609  Add the link to PR raised in week 2

**Comment by GeekGawd** [comment]
LGTM!

**Review by GeekGawd — APPROVED** [review]

**Comment by Sudheesh2609** [comment]
@GeekGawd  I have not raised any PR in week 2 (14-07-2023)
But I have mentioned PR in week 3. So I added the link there accordingly.
Please let me know if anything needs to be changed.
Thank you.

**Comment by GeekGawd** [comment]
> @GeekGawd I have not raised any PR in week 2 (14-07-2023) But I have mentioned PR in week 3. So I added the link there accordingly. Please let me know if anything needs to be changed. Thank you.

I mean to say in the learning section 

- BeckN Protocol: you can add short description about each like what new did you learn about them.

Also, kindly remove checkmarks from Learnings section don't really need them there

**Comment by Sudheesh2609** [comment]
> > @GeekGawd I have not raised any PR in week 2 (14-07-2023) But I have mentioned PR in week 3. So I added the link there accordingly. Please let me know if anything needs to be changed. Thank you.
> 
> I mean to say in the learning section
> 
> * BeckN Protocol: you can add short description about each like what new did you learn about them.
> 
> Also, kindly remove checkmarks from Learnings section don't really need them there

I have changed the learnings section in all weeks.
Please review once. Thank you.

**Comment by GeekGawd** [comment]
LGTM! Thank You! @Sudheesh2609

**Pull request merged**
