### PR TITLE
Venu choudhary/cord

### PR DESCRIPTION
**Pull request by VenuChoudhary001**
### Changes
Week 1-2-3 Milestones & Screenshots were added. 

### Notes
Some of the milestones have been distributed more properly now.

### CODE REVIEW

**Comment by GeekGawd** [comment]
@VenuChoudhary001 please include the media(images/videos) inside a folder (for example named assets)

**Comment by GeekGawd** [comment]
@VenuChoudhary001  
image

The link to images are broken the correct reltive url will be `./assets/`

**Comment by Vivek-Kumar-Shrivastav** [comment]
> The link to images are broken the correct reltive url will be `./assets/

Change the path of image:
From :  "docs/2023/CORD Network/IntegrationWithSunbirdRC/cord-chain.png" 
To :       "docs/2023/CORD Network/IntegrationWithSunbirdRC/assets/cord-chain.png" (exact path)
OR
To: "./assets/cord-chain.png" (relative path)

**Comment by GeekGawd** [comment]
Merged #281

**Pull request merged**
