### PR TITLE
Project: Ability to book an appointment via WhatsApp

### PR DESCRIPTION
**Pull request by Aniket28dot**
## Project

Ability to book an appointment via WhatsApp

### Changes

What was updated (initial updates, change author name and project name)

### Notes

If there are any further notes.

### CODE REVIEW

**Review by Apoorvgarg-creator — CHANGES_REQUESTED** [review]
kindly don't push yarn.lock and package-lock.json

**Comment by Aniket28dot** [comment]
> kindly don't push yarn.lock and package-lock.json

Hey can you review it again, I have updated the .gitignore

**Comment by Apoorvgarg-creator** [comment]
> > kindly don't push yarn.lock and package-lock.json
> 
> Hey can you review it again, I have updated the .gitignore

Those files are still there

**Comment by Aniket28dot** [comment]
> Those files are still there

Hii can you pls review it now. thanks.

**Pull request closed without merging**
