### PR TITLE
Beckn Mobility Platform

### PR DESCRIPTION
**Pull request by sniperzee2**
## Project

Beckn Mobility Platform

### Changes

Init and author change

### CODE REVIEW

**Comment by GeekGawd** [comment]
Please ammend your commit or and remove yarn.lock

**Comment by sniperzee2** [comment]
Can you please approve the changes @GeekGawd

**Comment by GeekGawd** [comment]
@sniperzee2 could you please correct the spelling beckn in slug

**Comment by sniperzee2** [comment]
@GeekGawd done

**Comment by sniperzee2** [comment]
@GeekGawd please merge my pr

**Pull request merged**
