### PR TITLE
Aayush Sharma(Sunbird Obsrv): added milestones, introduction and setup directory.

### PR DESCRIPTION
**Pull request by SuperAayush**
## Project

Sunbird Obsrv

### Changes

- Added the milestones directory
- Added the introduction directory
- Added the setup directory
- Updated the socials 
- Updated the author's name
- Updated the progress for week 1

### CODE REVIEW

**Comment by claddyk** [comment]
@SuperAayush Can you provide why you need to delete code from yarn.lock
I suggest that file not to be changed.

**Comment by SuperAayush** [comment]
> @SuperAayush Can you provide why you need to delete code from yarn.lock I suggest that file not to be changed.

I did not delete any set of code, I use npm and maybe some VSC extension did that.
Is that the reason for the deployment failure?

**Comment by shubhigupta991** [comment]
There are merge conflicts. Resolve them.

**Review by shubhigupta991 — CHANGES_REQUESTED** [review]
You have deleted contributions and screenshots section. Please do not delete them you can leave them empty

**Comment by SuperAayush** [comment]
> 

Ahh, I was having this intuition that it is failing because of that, will correct it and commit today!!

**Comment by SuperAayush** [comment]
Closing this one and going for a new PR

**Comment by SuperAayush** [comment]
Closing this one and going for a new PR

**Pull request closed without merging**
