### PR TITLE
changes made

### PR DESCRIPTION
**Pull request by kartiktongaria**
## Project

Name of the project

### Changes

What was updated (new pages, weekly update, etc.)

### Notes

If there are any further notes.

### CODE REVIEW

**Review by Apoorvgarg-creator — CHANGES_REQUESTED** [review]
Remove yarn.lock and and package-lock.json

**Comment by GeekGawd** [comment]
@kartiktongaria added some comments please check that, also put the images inside the assets folder and update the links. Do these changes I will handle the package and yarn issue myself.

**Comment by GeekGawd** [comment]
@kartiktongaria update the links to the assets now that you placed them inside the assets folder. Also, Add checkbox to the milestones

**Comment by Apoorvgarg-creator** [comment]
Steps, Download the yarn.lock or generate it. Simplest way is to go to your forked repo and there click on upload new file and just upload the file

**Comment by GeekGawd** [comment]
Merged with #315

**Pull request merged**
