### PR TITLE
Add project- Unnati

### PR DESCRIPTION
**Pull request by bhattabhi013**
## Project

Unnati 

### Changes

  Added weekly updates for Unnati

### CODE REVIEW

**Review by shubhigupta991 — APPROVED** [review]

**Comment by claddyk** [comment]
I'm not sure if unnati only has one project.
In case unnati has multiple projects you need to update your file names and structure accordingly.

**Comment by claddyk** [comment]
Unnati is not your project name.
Unnati is an organization and has the project [Implement Unnati standalone micro PWA](https://github.com/ELEVATE-Project/project-frontend/issues/1)

You need to update the folder structure and the file contents accordingly.

PS- In case I'm misunderstanding something leave a comment.

**Comment by bhattabhi013** [comment]
Hi @claddyk,
Shikshalokam is the organization and Unnati is the project's name.
I'm building this project from scratch.

**Review by shubhigupta991 — CHANGES_REQUESTED** [review]
you have deleted the slug line in docs/2023/Unnati/Unnati PWA/index.md file. Please re-write

**Comment by bhattabhi013** [comment]
> you have deleted the slug line in docs/2023/Unnati/Unnati PWA/index.md file. Please re-write

Needful done @shubhigupta991

**Review by Apoorvgarg-creator — APPROVED** [review]

**Pull request merged**
