### PR TITLE
Weekly Milestones update

### PR DESCRIPTION
**Pull request by godofgeeks23**
## Project

Name of the project

### Changes

What was updated (new pages, weekly update, etc.)

### Notes

If there are any further notes.

### CODE REVIEW

**Comment by GeekGawd** [comment]
@godofgeeks23 please put the media (images/videos) inside assets folder inside updates folder, you need to create an asset folder.

**Comment by GeekGawd** [comment]
The link to images are broken.

image


you need to do `./assets/` relative path for the correct linking.

**Comment by godofgeeks23** [comment]
@GeekGawd please check now

**Review by GeekGawd — APPROVED** [review]

**Comment by GeekGawd** [comment]
Merged with #282

**Pull request merged**
